name: Static-Analysis

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'check/**'
      - 'doc/**'
      - 'examples/**'
      - 'tools/**'

jobs:
  analize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update OS packages list
      run: |
        sudo apt-get update -yq
    - name: Install analyzer
      run: |
        sudo apt-get install -y cppcheck python3
        mkdir sa_results
    - name: General checks
      run: cppcheck --enable=all --inline-suppr  --inconclusive --std=c++11 ./src -I ./src/config -I ./src/include --output-file=./sa_results/general.txt --suppress=missingIncludeSystem --suppress=unmatchedSuppression:{} --suppress=unusedFunction:{}
    - uses: actions/upload-artifact@v4
      with:
        name: Static_Analisys_Results
        path: sa_results
    - name: Add static analysis results to summary
      run: |
        echo '## 🧪 Static Analysis Results' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat ./sa_results/general.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
